version: "3.7"

services:
  paper:
    build: .

    ports:
      - 25565:25565
    environment:
      JAVA_TOOL_OPTIONS: "-Xms1G -Xmx1G"
    volumes:
      - ./config/eula.txt:/app/eula.txt
      - ./data/world:/app/world
