version: "3.7"

services:
  paper:
    image: ghcr.io/sksat/papermc-docker:1.19.3@sha256:c9fe22b2f5c6f5745b396b26a7ec50a56537c77e3dd66837e2ff0f5ce7739eb0
    restart: always

    stdin_open: true
    ports:
      - 9225:9225
      - 25565:25565
      - 25575:25575
    environment:
      JAVA_TOOL_OPTIONS: "-Xms1G -Xmx1G"
    volumes:
      - ./data:/app
